# Array Introduction 

In [2]:
# array List
a = [1,2]
print("Array List ",a,"and its type", type(a))

# Array list Multiplication - Repeats
print("Repeats ",a*2)

# if we need multiplication in array we need to do, we could also use filter or map
print([x*2 for x in a ])

# Array List Addition - Concatenates
b = [3,4]
print("Concatenation",a+b)

Array List  [1, 2] and its type <class 'list'>
Repeats  [1, 2, 1, 2]
[2, 4]
Concatenation [1, 2, 3, 4]


### Numpy Array

In [8]:
import numpy as np 
arr= np.arange(100000)
my_list = list(range(100000))
%time for _ in range(10) : arr2= arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 2.45 ms
CPU times: user 68 ms, sys: 0 ns, total: 68 ms
Wall time: 70.1 ms


In [10]:
data= np.random.rand(2,3)
data = data* 10
data = data + data
print(data)

[[ 3.30396326  9.12981377  6.97727371]
 [18.25539659  7.59379702 17.05642737]]


In [ ]:
data = [6,7,8,9]
print(type(data))
data = np.array(data)
print(data.shape, type(data))

In [ ]:
data2 = [[1, 2, 3, 4], [5, 6, 7,7]]
new_arr = np.array(data2)
print(new_arr,new_arr.shape,type(new_arr))

In [ ]:
# Basic indexing and Slicing
arr= np.arange(10)
print(arr)
print(arr[5])
print(arr[4:9])

In [5]:
# Numpy array and its Operation
import numpy as np
a = np.array([1,2])
print("Numpy Array ",a,"and its type", type(a))
print("Multiplication with constant", a*2)
print("Addition with constant", 2+a)
b= np.array([3,4])
print("Addition with other Numpy Array", a+b)
print("Mulplication with Other Array", a*b) # here * mean component wise or else Voilation of Matrix multiplication
c = np.matmul(b,a)
print(c)

# We can also create numpy array using array list
c= [[1,2,3], [4,5,6]]

x= np.array(c)
print(x , x.ndim)

Numpy Array  [1 2] and its type <class 'numpy.ndarray'>
Multiplication with constant [2 4]
Addition with constant [3 4]
Addition with other Numpy Array [4 6]
Mulplication with Other Array [3 8]
11
[[1 2 3]
 [4 5 6]] 2
